name: Concurrency Demo

on:
  workflow_dispatch:

concurrency:
  group: main-branch-group
  cancel-in-progress: true

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running workflow"
      - run: sleep 180
      - run: echo "Finished"
