name: File operations in github

on: push

jobs:
  files:
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        run: echo "KK Devops 123456" > devops.txt

      - name: Display the content of the file
        run: cat devops.txt

      - name: Display the date
        run: date

      - name: Display files and directories
        run: ls -lrth

      - name: Display the present location
        run: pwd
