name: Workflow Level Env Example

on:
  workflow_dispatch:

env:
  BRAND: KKFUNDA
  PLATFORM: GitHub

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step in job1
        run: echo "Brand is $BRAND"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step in job2
        run: echo "Platform is $PLATFORM"
