name: Step Level Env Example

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Step level example
        env:
          CITY: Hyderabad
          TRAINER: Prashanth
        run: |
          echo "City is $CITY"
          echo "Trainer is $TRAINER"

      - name: Next step
        run: echo "City is $CITY and Trainer is $TRAINER"
