name: validating workflow without checkout

on: workflow_dispatch

jobs:
  files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v5

      - name: Display the content of the file
        run: cat devops.txt

      - name: Display the date
        run: |
         cat devops.txt
         pwd
         ls -lrth
         chmod +x uptime.sh
         ./uptime.sh
     


     
