name: validating workflow without checkout

on: workflow_dispatch

jobs:
  files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v5

      - name: Display the content of the file
        run: cat devops4.txt

      - name: Display the date
        run: date

     
