name: validating workflow without checkout

on: push

jobs:
  files:
    runs-on: ubuntu-latest
    steps:
      

      - name: Display the content of the file
        run: cat devops4.txt

      - name: Display the date
        run: date

     
